GET http://127.0.0.1:3001/v1/bakat40

###
GET http://127.0.0.1:3001/v1/bakat6

###
GET http://127.0.0.1:3001/v1/bakat3

###
GET http://127.0.0.1:3001/v1/perbaikan

###
GET http://127.0.0.1:3001/v1/result
###
GET http://127.0.0.1:3001/v1
###
POST http://127.0.0.1:3001/v1/result

content-type: application/json
{
    "nama": "sample",
    "skor40": [
        {
            "id":1,
            "skor":1
        },
        {
            "id":2,
            "skor":1
        },
        {
            "id":3,
            "skor":1
        },
        {
            "id":4,
            "skor":1
        },
        {
            "id":5,
            "skor":1
        },
        {
            "id":6,
            "skor":1
        },
        {
            "id":7,
            "skor":1
        },
        {
            "id":8,
            "skor":1
        },
        {
            "id":9,
            "skor":1
        },
        {
            "id":10,
            "skor":1
        },
        {
            "id":11,
            "skor":1
        },
        {
            "id":12,
            "skor":1
        },
        {
            "id":13,
            "skor":1
        },
        {
            "id":14,
            "skor":1
        },
        {
            "id":15,
            "skor":1
        },
        {
            "id":16,
            "skor":1
        },
        {
            "id":17,
            "skor":1
        },
        {
            "id":18,
            "skor":1
        },
        {
            "id":19,
            "skor":1
        },
        {
            "id":20,
            "skor":1
        },
        {
            "id":21,
            "skor":1
        },
        {
            "id":22,
            "skor":1
        },
        {
            "id":23,
            "skor":1
        },
        {
            "id":24,
            "skor":1
        },
        {
            "id":25,
            "skor":1
        },
        {
            "id":26,
            "skor":1
        },
        {
            "id":27,
            "skor":1
        },
        {
            "id":28,
            "skor":1
        },
        {
            "id":29,
            "skor":1
        },
        {
            "id":30,
            "skor":1
        },
        {
            "id":31,
            "skor":1
        },
        {
            "id":32,
            "skor":1
        },
        {
            "id":33,
            "skor":1
        },
        {
            "id":34,
            "skor":1
        },
        {
            "id":35,
            "skor":1
        },
        {
            "id":36,
            "skor":1
        },
        {
            "id":37,
            "skor":1
        },
        {
            "id":38,
            "skor":1
        },
        {
            "id":39,
            "skor":1
        },
        {
            "id":40,
            "skor":1
        },
        ]
}
