export const bakat18Array = [
  { id: 1, pribadi: 'bekerja keras karena ambisi' },
  { id: 2, pribadi: 'bekerja keras karena wibawa' },
  { id: 3, pribadi: 'bekerja keras karena giat bekerja' },
  { id: 4, pribadi: 'berpikir imajinatif' },
  { id: 5, pribadi: 'berpikir positif' },
  { id: 6, pribadi: 'berpikir analitis' },
  { id: 7, pribadi: 'apa adanya' },
  { id: 8, pribadi: 'berdiam diri' },
  { id: 9, pribadi: 'merendah' },
  { id: 10, pribadi: 'mempengaruhi dengan cara menguasai' },
  { id: 11, pribadi: 'mempengaruhi dengan cara memotivasi' },
  { id: 12, pribadi: 'mempengaruhi dengan cara menolong' },
  { id: 13, pribadi: 'memanfaatkan hubungan' },
  { id: 14, pribadi: 'memulai hubungan baru' },
  { id: 15, pribadi: 'menguatkan hubungan yang ada' },
  { id: 16, pribadi: 'melayani dengan cara memberi' },
  { id: 17, pribadi: 'melayani dengan cara menjaga' },
  { id: 18, pribadi: 'melayani dengan cara mengalah' },
];
