type PerbaikanBakat40 = {
  id: number;
  bakat40: { id: number };
  bakat40_perbaikan: { id: number };
  perbaikan: string;
};

export const perbaikanBakat40: PerbaikanBakat40[] = [
  {
    id: 1,
    bakat40: { id: 1 },
    bakat40_perbaikan: { id: 17 },
    perbaikan: 'lalai',
  },
  {
    id: 2,
    bakat40: { id: 1 },
    bakat40_perbaikan: { id: 29 },
    perbaikan: 'lalai',
  },
  {
    id: 3,
    bakat40: { id: 1 },
    bakat40_perbaikan: { id: 32 },
    perbaikan: 'lalai',
  },
  {
    id: 4,
    bakat40: { id: 1 },
    bakat40_perbaikan: { id: 12 },
    perbaikan: 'lalai',
  },
  {
    id: 5,
    bakat40: { id: 1 },
    bakat40_perbaikan: { id: 3 },
    perbaikan: 'lalai',
  },
  {
    id: 6,
    bakat40: { id: 1 },
    bakat40_perbaikan: { id: 2 },
    perbaikan: 'lalai',
  },
  {
    id: 7,
    bakat40: { id: 1 },
    bakat40_perbaikan: { id: 35 },
    perbaikan: 'berlebihan',
  },
  {
    id: 8,
    bakat40: { id: 1 },
    bakat40_perbaikan: { id: 22 },
    perbaikan: 'berlebihan',
  },
  {
    id: 9,
    bakat40: { id: 1 },
    bakat40_perbaikan: { id: 9 },
    perbaikan: 'berlebihan',
  },
  {
    id: 10,
    bakat40: { id: 2 },
    bakat40_perbaikan: { id: 34 },
    perbaikan: 'lalai',
  },
  {
    id: 11,
    bakat40: { id: 2 },
    bakat40_perbaikan: { id: 15 },
    perbaikan: 'lalai',
  },
  {
    id: 12,
    bakat40: { id: 2 },
    bakat40_perbaikan: { id: 18 },
    perbaikan: 'berlebihan',
  },
  {
    id: 13,
    bakat40: { id: 2 },
    bakat40_perbaikan: { id: 40 },
    perbaikan: 'berlebihan',
  },
  {
    id: 14,
    bakat40: { id: 3 },
    bakat40_perbaikan: { id: 12 },
    perbaikan: 'lalai',
  },
  {
    id: 15,
    bakat40: { id: 3 },
    bakat40_perbaikan: { id: 14 },
    perbaikan: 'berlebihan',
  },
  {
    id: 16,
    bakat40: { id: 3 },
    bakat40_perbaikan: { id: 8 },
    perbaikan: 'berlebihan',
  },
  {
    id: 17,
    bakat40: { id: 4 },
    bakat40_perbaikan: { id: 25 },
    perbaikan: 'lalai',
  },
  {
    id: 18,
    bakat40: { id: 4 },
    bakat40_perbaikan: { id: 13 },
    perbaikan: 'lalai',
  },
  {
    id: 19,
    bakat40: { id: 4 },
    bakat40_perbaikan: { id: 28 },
    perbaikan: 'berlebihan',
  },
  {
    id: 20,
    bakat40: { id: 4 },
    bakat40_perbaikan: { id: 37 },
    perbaikan: 'berlebihan',
  },
  {
    id: 21,
    bakat40: { id: 4 },
    bakat40_perbaikan: { id: 10 },
    perbaikan: 'berlebihan',
  },
  {
    id: 22,
    bakat40: { id: 5 },
    bakat40_perbaikan: { id: 30 },
    perbaikan: 'lalai',
  },
  {
    id: 23,
    bakat40: { id: 5 },
    bakat40_perbaikan: { id: 23 },
    perbaikan: 'lalai',
  },
  {
    id: 24,
    bakat40: { id: 5 },
    bakat40_perbaikan: { id: 38 },
    perbaikan: 'lalai',
  },
  {
    id: 25,
    bakat40: { id: 5 },
    bakat40_perbaikan: { id: 35 },
    perbaikan: 'berlebihan',
  },
  {
    id: 26,
    bakat40: { id: 5 },
    bakat40_perbaikan: { id: 22 },
    perbaikan: 'berlebihan',
  },
  {
    id: 27,
    bakat40: { id: 5 },
    bakat40_perbaikan: { id: 9 },
    perbaikan: 'berlebihan',
  },
  {
    id: 28,
    bakat40: { id: 6 },
    bakat40_perbaikan: { id: 11 },
    perbaikan: 'lalai',
  },
  {
    id: 29,
    bakat40: { id: 6 },
    bakat40_perbaikan: { id: 37 },
    perbaikan: 'berlebihan',
  },
  {
    id: 30,
    bakat40: { id: 6 },
    bakat40_perbaikan: { id: 28 },
    perbaikan: 'berlebihan',
  },
  {
    id: 31,
    bakat40: { id: 6 },
    bakat40_perbaikan: { id: 10 },
    perbaikan: 'berlebihan',
  },
  {
    id: 32,
    bakat40: { id: 7 },
    bakat40_perbaikan: { id: 35 },
    perbaikan: 'lalai',
  },
  {
    id: 33,
    bakat40: { id: 7 },
    bakat40_perbaikan: { id: 12 },
    perbaikan: 'berlebihan',
  },
  {
    id: 34,
    bakat40: { id: 7 },
    bakat40_perbaikan: { id: 17 },
    perbaikan: 'berlebihan',
  },
  {
    id: 35,
    bakat40: { id: 7 },
    bakat40_perbaikan: { id: 29 },
    perbaikan: 'berlebihan',
  },
  {
    id: 36,
    bakat40: { id: 7 },
    bakat40_perbaikan: { id: 32 },
    perbaikan: 'berlebihan',
  },
  {
    id: 37,
    bakat40: { id: 8 },
    bakat40_perbaikan: { id: 11 },
    perbaikan: 'lalai',
  },
  {
    id: 38,
    bakat40: { id: 8 },
    bakat40_perbaikan: { id: 6 },
    perbaikan: 'lalai',
  },
  {
    id: 39,
    bakat40: { id: 8 },
    bakat40_perbaikan: { id: 34 },
    perbaikan: 'berlebihan',
  },
  {
    id: 40,
    bakat40: { id: 8 },
    bakat40_perbaikan: { id: 33 },
    perbaikan: 'berlebihan',
  },
  {
    id: 41,
    bakat40: { id: 8 },
    bakat40_perbaikan: { id: 15 },
    perbaikan: 'berlebihan',
  },
  {
    id: 42,
    bakat40: { id: 9 },
    bakat40_perbaikan: { id: 22 },
    perbaikan: 'lalai',
  },
  {
    id: 43,
    bakat40: { id: 9 },
    bakat40_perbaikan: { id: 35 },
    perbaikan: 'lalai',
  },
  {
    id: 44,
    bakat40: { id: 9 },
    bakat40_perbaikan: { id: 37 },
    perbaikan: 'berlebihan',
  },
  {
    id: 45,
    bakat40: { id: 9 },
    bakat40_perbaikan: { id: 28 },
    perbaikan: 'berlebihan',
  },
  {
    id: 46,
    bakat40: { id: 9 },
    bakat40_perbaikan: { id: 10 },
    perbaikan: 'berlebihan',
  },
  {
    id: 47,
    bakat40: { id: 10 },
    bakat40_perbaikan: { id: 15 },
    perbaikan: 'lalai',
  },
  {
    id: 48,
    bakat40: { id: 10 },
    bakat40_perbaikan: { id: 34 },
    perbaikan: 'lalai',
  },
  {
    id: 49,
    bakat40: { id: 10 },
    bakat40_perbaikan: { id: 13 },
    perbaikan: 'berlebihan',
  },
  {
    id: 50,
    bakat40: { id: 10 },
    bakat40_perbaikan: { id: 4 },
    perbaikan: 'berlebihan',
  },
  {
    id: 51,
    bakat40: { id: 10 },
    bakat40_perbaikan: { id: 25 },
    perbaikan: 'berlebihan',
  },
  {
    id: 52,
    bakat40: { id: 10 },
    bakat40_perbaikan: { id: 16 },
    perbaikan: 'berlebihan',
  },
  {
    id: 53,
    bakat40: { id: 10 },
    bakat40_perbaikan: { id: 18 },
    perbaikan: 'berlebihan',
  },
  {
    id: 54,
    bakat40: { id: 10 },
    bakat40_perbaikan: { id: 40 },
    perbaikan: 'berlebihan',
  },
  {
    id: 55,
    bakat40: { id: 11 },
    bakat40_perbaikan: { id: 6 },
    perbaikan: 'lalai',
  },
  {
    id: 56,
    bakat40: { id: 11 },
    bakat40_perbaikan: { id: 26 },
    perbaikan: 'lalai',
  },
  {
    id: 57,
    bakat40: { id: 11 },
    bakat40_perbaikan: { id: 14 },
    perbaikan: 'lalai',
  },
  {
    id: 58,
    bakat40: { id: 11 },
    bakat40_perbaikan: { id: 8 },
    perbaikan: 'lalai',
  },
  {
    id: 59,
    bakat40: { id: 11 },
    bakat40_perbaikan: { id: 34 },
    perbaikan: 'berlebihan',
  },
  {
    id: 60,
    bakat40: { id: 11 },
    bakat40_perbaikan: { id: 15 },
    perbaikan: 'berlebihan',
  },
  {
    id: 61,
    bakat40: { id: 12 },
    bakat40_perbaikan: { id: 32 },
    perbaikan: 'lalai',
  },
  {
    id: 62,
    bakat40: { id: 12 },
    bakat40_perbaikan: { id: 3 },
    perbaikan: 'lalai',
  },
  {
    id: 63,
    bakat40: { id: 12 },
    bakat40_perbaikan: { id: 35 },
    perbaikan: 'berlebihan',
  },
  {
    id: 64,
    bakat40: { id: 12 },
    bakat40_perbaikan: { id: 22 },
    perbaikan: 'berlebihan',
  },
  {
    id: 65,
    bakat40: { id: 12 },
    bakat40_perbaikan: { id: 9 },
    perbaikan: 'berlebihan',
  },
  {
    id: 66,
    bakat40: { id: 13 },
    bakat40_perbaikan: { id: 4 },
    perbaikan: 'lalai',
  },
  {
    id: 67,
    bakat40: { id: 13 },
    bakat40_perbaikan: { id: 25 },
    perbaikan: 'lalai',
  },
  {
    id: 68,
    bakat40: { id: 13 },
    bakat40_perbaikan: { id: 28 },
    perbaikan: 'berlebihan',
  },
  {
    id: 69,
    bakat40: { id: 13 },
    bakat40_perbaikan: { id: 37 },
    perbaikan: 'berlebihan',
  },
  {
    id: 70,
    bakat40: { id: 13 },
    bakat40_perbaikan: { id: 10 },
    perbaikan: 'berlebihan',
  },
  {
    id: 71,
    bakat40: { id: 14 },
    bakat40_perbaikan: { id: 11 },
    perbaikan: 'lalai',
  },
  {
    id: 72,
    bakat40: { id: 14 },
    bakat40_perbaikan: { id: 8 },
    perbaikan: 'lalai',
  },
  {
    id: 73,
    bakat40: { id: 14 },
    bakat40_perbaikan: { id: 18 },
    perbaikan: 'berlebihan',
  },
  {
    id: 74,
    bakat40: { id: 14 },
    bakat40_perbaikan: { id: 4 },
    perbaikan: 'berlebihan',
  },
  {
    id: 75,
    bakat40: { id: 14 },
    bakat40_perbaikan: { id: 13 },
    perbaikan: 'berlebihan',
  },
  {
    id: 76,
    bakat40: { id: 14 },
    bakat40_perbaikan: { id: 40 },
    perbaikan: 'berlebihan',
  },
  {
    id: 77,
    bakat40: { id: 15 },
    bakat40_perbaikan: { id: 10 },
    perbaikan: 'lalai',
  },
  {
    id: 78,
    bakat40: { id: 15 },
    bakat40_perbaikan: { id: 37 },
    perbaikan: 'lalai',
  },
  {
    id: 79,
    bakat40: { id: 15 },
    bakat40_perbaikan: { id: 28 },
    perbaikan: 'lalai',
  },
  {
    id: 80,
    bakat40: { id: 15 },
    bakat40_perbaikan: { id: 34 },
    perbaikan: 'lalai',
  },
  {
    id: 81,
    bakat40: { id: 15 },
    bakat40_perbaikan: { id: 13 },
    perbaikan: 'berlebihan',
  },
  {
    id: 82,
    bakat40: { id: 15 },
    bakat40_perbaikan: { id: 4 },
    perbaikan: 'berlebihan',
  },
  {
    id: 83,
    bakat40: { id: 15 },
    bakat40_perbaikan: { id: 18 },
    perbaikan: 'berlebihan',
  },
  {
    id: 84,
    bakat40: { id: 15 },
    bakat40_perbaikan: { id: 40 },
    perbaikan: 'berlebihan',
  },
  {
    id: 85,
    bakat40: { id: 16 },
    bakat40_perbaikan: { id: 13 },
    perbaikan: 'lalai',
  },
  {
    id: 86,
    bakat40: { id: 16 },
    bakat40_perbaikan: { id: 4 },
    perbaikan: 'lalai',
  },
  {
    id: 87,
    bakat40: { id: 16 },
    bakat40_perbaikan: { id: 25 },
    perbaikan: 'lalai',
  },
  {
    id: 88,
    bakat40: { id: 16 },
    bakat40_perbaikan: { id: 18 },
    perbaikan: 'lalai',
  },
  {
    id: 89,
    bakat40: { id: 16 },
    bakat40_perbaikan: { id: 40 },
    perbaikan: 'lalai',
  },
  {
    id: 90,
    bakat40: { id: 16 },
    bakat40_perbaikan: { id: 28 },
    perbaikan: 'berlebihan',
  },
  {
    id: 91,
    bakat40: { id: 16 },
    bakat40_perbaikan: { id: 37 },
    perbaikan: 'berlebihan',
  },
  {
    id: 92,
    bakat40: { id: 17 },
    bakat40_perbaikan: { id: 19 },
    perbaikan: 'lalai',
  },
  {
    id: 93,
    bakat40: { id: 17 },
    bakat40_perbaikan: { id: 27 },
    perbaikan: 'lalai',
  },
  {
    id: 94,
    bakat40: { id: 17 },
    bakat40_perbaikan: { id: 24 },
    perbaikan: 'lalai',
  },
  {
    id: 95,
    bakat40: { id: 17 },
    bakat40_perbaikan: { id: 35 },
    perbaikan: 'berlebihan',
  },
  {
    id: 96,
    bakat40: { id: 17 },
    bakat40_perbaikan: { id: 22 },
    perbaikan: 'berlebihan',
  },
  {
    id: 97,
    bakat40: { id: 17 },
    bakat40_perbaikan: { id: 9 },
    perbaikan: 'berlebihan',
  },
  {
    id: 98,
    bakat40: { id: 18 },
    bakat40_perbaikan: { id: 13 },
    perbaikan: 'lalai',
  },
  {
    id: 99,
    bakat40: { id: 18 },
    bakat40_perbaikan: { id: 4 },
    perbaikan: 'lalai',
  },
  {
    id: 100,
    bakat40: { id: 18 },
    bakat40_perbaikan: { id: 25 },
    perbaikan: 'lalai',
  },
  {
    id: 101,
    bakat40: { id: 18 },
    bakat40_perbaikan: { id: 16 },
    perbaikan: 'lalai',
  },
  {
    id: 102,
    bakat40: { id: 18 },
    bakat40_perbaikan: { id: 40 },
    perbaikan: 'lalai',
  },
  {
    id: 103,
    bakat40: { id: 18 },
    bakat40_perbaikan: { id: 37 },
    perbaikan: 'berlebihan',
  },
  {
    id: 104,
    bakat40: { id: 18 },
    bakat40_perbaikan: { id: 28 },
    perbaikan: 'berlebihan',
  },
  {
    id: 105,
    bakat40: { id: 18 },
    bakat40_perbaikan: { id: 10 },
    perbaikan: 'berlebihan',
  },
  {
    id: 106,
    bakat40: { id: 19 },
    bakat40_perbaikan: { id: 27 },
    perbaikan: 'lalai',
  },
  {
    id: 107,
    bakat40: { id: 19 },
    bakat40_perbaikan: { id: 24 },
    perbaikan: 'lalai',
  },
  {
    id: 108,
    bakat40: { id: 19 },
    bakat40_perbaikan: { id: 28 },
    perbaikan: 'berlebihan',
  },
  {
    id: 109,
    bakat40: { id: 19 },
    bakat40_perbaikan: { id: 37 },
    perbaikan: 'berlebihan',
  },
  {
    id: 110,
    bakat40: { id: 19 },
    bakat40_perbaikan: { id: 10 },
    perbaikan: 'berlebihan',
  },
  {
    id: 111,
    bakat40: { id: 20 },
    bakat40_perbaikan: { id: 2 },
    perbaikan: 'lalai',
  },
  {
    id: 112,
    bakat40: { id: 20 },
    bakat40_perbaikan: { id: 31 },
    perbaikan: 'lalai',
  },
  {
    id: 113,
    bakat40: { id: 20 },
    bakat40_perbaikan: { id: 19 },
    perbaikan: 'berlebihan',
  },
  {
    id: 114,
    bakat40: { id: 20 },
    bakat40_perbaikan: { id: 27 },
    perbaikan: 'berlebihan',
  },
  {
    id: 115,
    bakat40: { id: 20 },
    bakat40_perbaikan: { id: 24 },
    perbaikan: 'berlebihan',
  },
  {
    id: 116,
    bakat40: { id: 20 },
    bakat40_perbaikan: { id: 7 },
    perbaikan: 'berlebihan',
  },
  {
    id: 117,
    bakat40: { id: 21 },
    bakat40_perbaikan: { id: 38 },
    perbaikan: 'lalai',
  },
  {
    id: 118,
    bakat40: { id: 21 },
    bakat40_perbaikan: { id: 36 },
    perbaikan: 'lalai',
  },
  {
    id: 119,
    bakat40: { id: 21 },
    bakat40_perbaikan: { id: 5 },
    perbaikan: 'lalai',
  },
  {
    id: 120,
    bakat40: { id: 21 },
    bakat40_perbaikan: { id: 18 },
    perbaikan: 'berlebihan',
  },
  {
    id: 121,
    bakat40: { id: 21 },
    bakat40_perbaikan: { id: 40 },
    perbaikan: 'berlebihan',
  },
  {
    id: 122,
    bakat40: { id: 22 },
    bakat40_perbaikan: { id: 9 },
    perbaikan: 'lalai',
  },
  {
    id: 123,
    bakat40: { id: 22 },
    bakat40_perbaikan: { id: 35 },
    perbaikan: 'lalai',
  },
  {
    id: 124,
    bakat40: { id: 22 },
    bakat40_perbaikan: { id: 13 },
    perbaikan: 'lalai',
  },
  {
    id: 125,
    bakat40: { id: 22 },
    bakat40_perbaikan: { id: 16 },
    perbaikan: 'lalai',
  },
  {
    id: 126,
    bakat40: { id: 22 },
    bakat40_perbaikan: { id: 25 },
    perbaikan: 'lalai',
  },
  {
    id: 127,
    bakat40: { id: 22 },
    bakat40_perbaikan: { id: 1 },
    perbaikan: 'berlebihan',
  },
  {
    id: 128,
    bakat40: { id: 22 },
    bakat40_perbaikan: { id: 17 },
    perbaikan: 'berlebihan',
  },
  {
    id: 129,
    bakat40: { id: 22 },
    bakat40_perbaikan: { id: 29 },
    perbaikan: 'berlebihan',
  },
  {
    id: 130,
    bakat40: { id: 22 },
    bakat40_perbaikan: { id: 28 },
    perbaikan: 'berlebihan',
  },
  {
    id: 131,
    bakat40: { id: 22 },
    bakat40_perbaikan: { id: 37 },
    perbaikan: 'berlebihan',
  },
  {
    id: 132,
    bakat40: { id: 23 },
    bakat40_perbaikan: { id: 5 },
    perbaikan: 'lalai',
  },
  {
    id: 133,
    bakat40: { id: 23 },
    bakat40_perbaikan: { id: 30 },
    perbaikan: 'lalai',
  },
  {
    id: 134,
    bakat40: { id: 23 },
    bakat40_perbaikan: { id: 21 },
    perbaikan: 'lalai',
  },
  {
    id: 135,
    bakat40: { id: 23 },
    bakat40_perbaikan: { id: 33 },
    perbaikan: 'berlebihan',
  },
  {
    id: 136,
    bakat40: { id: 23 },
    bakat40_perbaikan: { id: 15 },
    perbaikan: 'berlebihan',
  },
  {
    id: 137,
    bakat40: { id: 23 },
    bakat40_perbaikan: { id: 34 },
    perbaikan: 'berlebihan',
  },
  {
    id: 138,
    bakat40: { id: 24 },
    bakat40_perbaikan: { id: 27 },
    perbaikan: 'lalai',
  },
  {
    id: 139,
    bakat40: { id: 24 },
    bakat40_perbaikan: { id: 19 },
    perbaikan: 'lalai',
  },
  {
    id: 140,
    bakat40: { id: 24 },
    bakat40_perbaikan: { id: 30 },
    perbaikan: 'berlebihan',
  },
  {
    id: 141,
    bakat40: { id: 24 },
    bakat40_perbaikan: { id: 21 },
    perbaikan: 'berlebihan',
  },
  {
    id: 142,
    bakat40: { id: 24 },
    bakat40_perbaikan: { id: 29 },
    perbaikan: 'berlebihan',
  },
  {
    id: 143,
    bakat40: { id: 24 },
    bakat40_perbaikan: { id: 17 },
    perbaikan: 'berlebihan',
  },
  {
    id: 144,
    bakat40: { id: 25 },
    bakat40_perbaikan: { id: 13 },
    perbaikan: 'lalai',
  },
  {
    id: 145,
    bakat40: { id: 25 },
    bakat40_perbaikan: { id: 16 },
    perbaikan: 'lalai',
  },
  {
    id: 146,
    bakat40: { id: 25 },
    bakat40_perbaikan: { id: 4 },
    perbaikan: 'lalai',
  },
  {
    id: 147,
    bakat40: { id: 25 },
    bakat40_perbaikan: { id: 28 },
    perbaikan: 'berlebihan',
  },
  {
    id: 148,
    bakat40: { id: 25 },
    bakat40_perbaikan: { id: 37 },
    perbaikan: 'berlebihan',
  },
  {
    id: 149,
    bakat40: { id: 26 },
    bakat40_perbaikan: { id: 8 },
    perbaikan: 'lalai',
  },
  {
    id: 150,
    bakat40: { id: 26 },
    bakat40_perbaikan: { id: 14 },
    perbaikan: 'lalai',
  },
  {
    id: 151,
    bakat40: { id: 26 },
    bakat40_perbaikan: { id: 34 },
    perbaikan: 'berlebihan',
  },
  {
    id: 152,
    bakat40: { id: 26 },
    bakat40_perbaikan: { id: 33 },
    perbaikan: 'berlebihan',
  },
  {
    id: 153,
    bakat40: { id: 26 },
    bakat40_perbaikan: { id: 15 },
    perbaikan: 'berlebihan',
  },
  {
    id: 154,
    bakat40: { id: 26 },
    bakat40_perbaikan: { id: 10 },
    perbaikan: 'berlebihan',
  },
  {
    id: 155,
    bakat40: { id: 27 },
    bakat40_perbaikan: { id: 19 },
    perbaikan: 'lalai',
  },
  {
    id: 156,
    bakat40: { id: 27 },
    bakat40_perbaikan: { id: 24 },
    perbaikan: 'lalai',
  },
  {
    id: 157,
    bakat40: { id: 27 },
    bakat40_perbaikan: { id: 1 },
    perbaikan: 'berlebihan',
  },
  {
    id: 158,
    bakat40: { id: 27 },
    bakat40_perbaikan: { id: 17 },
    perbaikan: 'berlebihan',
  },
  {
    id: 159,
    bakat40: { id: 27 },
    bakat40_perbaikan: { id: 29 },
    perbaikan: 'berlebihan',
  },
  {
    id: 160,
    bakat40: { id: 27 },
    bakat40_perbaikan: { id: 28 },
    perbaikan: 'berlebihan',
  },
  {
    id: 161,
    bakat40: { id: 27 },
    bakat40_perbaikan: { id: 37 },
    perbaikan: 'berlebihan',
  },
  {
    id: 162,
    bakat40: { id: 28 },
    bakat40_perbaikan: { id: 37 },
    perbaikan: 'lalai',
  },
  {
    id: 163,
    bakat40: { id: 28 },
    bakat40_perbaikan: { id: 13 },
    perbaikan: 'berlebihan',
  },
  {
    id: 164,
    bakat40: { id: 28 },
    bakat40_perbaikan: { id: 16 },
    perbaikan: 'berlebihan',
  },
  {
    id: 165,
    bakat40: { id: 28 },
    bakat40_perbaikan: { id: 4 },
    perbaikan: 'berlebihan',
  },
  {
    id: 166,
    bakat40: { id: 28 },
    bakat40_perbaikan: { id: 25 },
    perbaikan: 'berlebihan',
  },
  {
    id: 167,
    bakat40: { id: 28 },
    bakat40_perbaikan: { id: 18 },
    perbaikan: 'berlebihan',
  },
  {
    id: 168,
    bakat40: { id: 28 },
    bakat40_perbaikan: { id: 40 },
    perbaikan: 'berlebihan',
  },
  {
    id: 169,
    bakat40: { id: 29 },
    bakat40_perbaikan: { id: 17 },
    perbaikan: 'lalai',
  },
  {
    id: 170,
    bakat40: { id: 29 },
    bakat40_perbaikan: { id: 12 },
    perbaikan: 'lalai',
  },
  {
    id: 171,
    bakat40: { id: 29 },
    bakat40_perbaikan: { id: 18 },
    perbaikan: 'berlebihan',
  },
  {
    id: 172,
    bakat40: { id: 29 },
    bakat40_perbaikan: { id: 40 },
    perbaikan: 'berlebihan',
  },
  {
    id: 173,
    bakat40: { id: 30 },
    bakat40_perbaikan: { id: 5 },
    perbaikan: 'lalai',
  },
  {
    id: 174,
    bakat40: { id: 30 },
    bakat40_perbaikan: { id: 21 },
    perbaikan: 'lalai',
  },
  {
    id: 175,
    bakat40: { id: 30 },
    bakat40_perbaikan: { id: 35 },
    perbaikan: 'berlebihan',
  },
  {
    id: 176,
    bakat40: { id: 30 },
    bakat40_perbaikan: { id: 9 },
    perbaikan: 'berlebihan',
  },
  {
    id: 177,
    bakat40: { id: 30 },
    bakat40_perbaikan: { id: 22 },
    perbaikan: 'berlebihan',
  },
  {
    id: 178,
    bakat40: { id: 31 },
    bakat40_perbaikan: { id: 20 },
    perbaikan: 'lalai',
  },
  {
    id: 179,
    bakat40: { id: 31 },
    bakat40_perbaikan: { id: 2 },
    perbaikan: 'lalai',
  },
  {
    id: 180,
    bakat40: { id: 31 },
    bakat40_perbaikan: { id: 32 },
    perbaikan: 'lalai',
  },
  {
    id: 181,
    bakat40: { id: 31 },
    bakat40_perbaikan: { id: 7 },
    perbaikan: 'berlebihan',
  },
  {
    id: 182,
    bakat40: { id: 31 },
    bakat40_perbaikan: { id: 24 },
    perbaikan: 'berlebihan',
  },
  {
    id: 183,
    bakat40: { id: 32 },
    bakat40_perbaikan: { id: 3 },
    perbaikan: 'lalai',
  },
  {
    id: 184,
    bakat40: { id: 32 },
    bakat40_perbaikan: { id: 12 },
    perbaikan: 'lalai',
  },
  {
    id: 185,
    bakat40: { id: 32 },
    bakat40_perbaikan: { id: 35 },
    perbaikan: 'berlebihan',
  },
  {
    id: 186,
    bakat40: { id: 32 },
    bakat40_perbaikan: { id: 9 },
    perbaikan: 'berlebihan',
  },
  {
    id: 187,
    bakat40: { id: 32 },
    bakat40_perbaikan: { id: 22 },
    perbaikan: 'berlebihan',
  },
  {
    id: 188,
    bakat40: { id: 33 },
    bakat40_perbaikan: { id: 34 },
    perbaikan: 'lalai',
  },
  {
    id: 189,
    bakat40: { id: 33 },
    bakat40_perbaikan: { id: 15 },
    perbaikan: 'lalai',
  },
  {
    id: 190,
    bakat40: { id: 33 },
    bakat40_perbaikan: { id: 10 },
    perbaikan: 'lalai',
  },
  {
    id: 191,
    bakat40: { id: 33 },
    bakat40_perbaikan: { id: 35 },
    perbaikan: 'berlebihan',
  },
  {
    id: 192,
    bakat40: { id: 33 },
    bakat40_perbaikan: { id: 9 },
    perbaikan: 'berlebihan',
  },
  {
    id: 193,
    bakat40: { id: 33 },
    bakat40_perbaikan: { id: 22 },
    perbaikan: 'berlebihan',
  },
  {
    id: 194,
    bakat40: { id: 34 },
    bakat40_perbaikan: { id: 15 },
    perbaikan: 'lalai',
  },
  {
    id: 195,
    bakat40: { id: 34 },
    bakat40_perbaikan: { id: 33 },
    perbaikan: 'lalai',
  },
  {
    id: 196,
    bakat40: { id: 34 },
    bakat40_perbaikan: { id: 18 },
    perbaikan: 'berlebihan',
  },
  {
    id: 197,
    bakat40: { id: 34 },
    bakat40_perbaikan: { id: 40 },
    perbaikan: 'berlebihan',
  },
  {
    id: 198,
    bakat40: { id: 34 },
    bakat40_perbaikan: { id: 35 },
    perbaikan: 'berlebihan',
  },
  {
    id: 199,
    bakat40: { id: 35 },
    bakat40_perbaikan: { id: 9 },
    perbaikan: 'lalai',
  },
  {
    id: 200,
    bakat40: { id: 35 },
    bakat40_perbaikan: { id: 22 },
    perbaikan: 'lalai',
  },
  {
    id: 201,
    bakat40: { id: 35 },
    bakat40_perbaikan: { id: 13 },
    perbaikan: 'lalai',
  },
  {
    id: 202,
    bakat40: { id: 35 },
    bakat40_perbaikan: { id: 16 },
    perbaikan: 'lalai',
  },
  {
    id: 203,
    bakat40: { id: 35 },
    bakat40_perbaikan: { id: 4 },
    perbaikan: 'lalai',
  },
  {
    id: 204,
    bakat40: { id: 35 },
    bakat40_perbaikan: { id: 32 },
    perbaikan: 'berlebihan',
  },
  {
    id: 205,
    bakat40: { id: 35 },
    bakat40_perbaikan: { id: 12 },
    perbaikan: 'berlebihan',
  },
  {
    id: 206,
    bakat40: { id: 35 },
    bakat40_perbaikan: { id: 3 },
    perbaikan: 'berlebihan',
  },
  {
    id: 207,
    bakat40: { id: 36 },
    bakat40_perbaikan: { id: 1 },
    perbaikan: 'lalai',
  },
  {
    id: 208,
    bakat40: { id: 36 },
    bakat40_perbaikan: { id: 38 },
    perbaikan: 'lalai',
  },
  {
    id: 209,
    bakat40: { id: 36 },
    bakat40_perbaikan: { id: 35 },
    perbaikan: 'berlebihan',
  },
  {
    id: 210,
    bakat40: { id: 36 },
    bakat40_perbaikan: { id: 9 },
    perbaikan: 'berlebihan',
  },
  {
    id: 211,
    bakat40: { id: 36 },
    bakat40_perbaikan: { id: 22 },
    perbaikan: 'berlebihan',
  },
  {
    id: 212,
    bakat40: { id: 37 },
    bakat40_perbaikan: { id: 28 },
    perbaikan: 'lalai',
  },
  {
    id: 213,
    bakat40: { id: 37 },
    bakat40_perbaikan: { id: 10 },
    perbaikan: 'lalai',
  },
  {
    id: 214,
    bakat40: { id: 37 },
    bakat40_perbaikan: { id: 35 },
    perbaikan: 'berlebihan',
  },
  {
    id: 215,
    bakat40: { id: 37 },
    bakat40_perbaikan: { id: 9 },
    perbaikan: 'berlebihan',
  },
  {
    id: 216,
    bakat40: { id: 37 },
    bakat40_perbaikan: { id: 22 },
    perbaikan: 'berlebihan',
  },
  {
    id: 217,
    bakat40: { id: 38 },
    bakat40_perbaikan: { id: 36 },
    perbaikan: 'lalai',
  },
  {
    id: 218,
    bakat40: { id: 38 },
    bakat40_perbaikan: { id: 1 },
    perbaikan: 'lalai',
  },
  {
    id: 219,
    bakat40: { id: 38 },
    bakat40_perbaikan: { id: 18 },
    perbaikan: 'berlebihan',
  },
  {
    id: 220,
    bakat40: { id: 38 },
    bakat40_perbaikan: { id: 40 },
    perbaikan: 'berlebihan',
  },
  {
    id: 221,
    bakat40: { id: 39 },
    bakat40_perbaikan: { id: 34 },
    perbaikan: 'lalai',
  },
  {
    id: 222,
    bakat40: { id: 39 },
    bakat40_perbaikan: { id: 10 },
    perbaikan: 'lalai',
  },
  {
    id: 223,
    bakat40: { id: 39 },
    bakat40_perbaikan: { id: 15 },
    perbaikan: 'lalai',
  },
  {
    id: 224,
    bakat40: { id: 39 },
    bakat40_perbaikan: { id: 18 },
    perbaikan: 'berlebihan',
  },
  {
    id: 225,
    bakat40: { id: 39 },
    bakat40_perbaikan: { id: 40 },
    perbaikan: 'berlebihan',
  },
  {
    id: 226,
    bakat40: { id: 40 },
    bakat40_perbaikan: { id: 18 },
    perbaikan: 'lalai',
  },
  {
    id: 227,
    bakat40: { id: 40 },
    bakat40_perbaikan: { id: 4 },
    perbaikan: 'lalai',
  },
  {
    id: 228,
    bakat40: { id: 40 },
    bakat40_perbaikan: { id: 37 },
    perbaikan: 'berlebihan',
  },
  {
    id: 229,
    bakat40: { id: 40 },
    bakat40_perbaikan: { id: 28 },
    perbaikan: 'berlebihan',
  },
];
